### ISSUE TITLE
Google Maps crashes.. 

### ISSUE THREAD

**Issue by Cris--** [gloeyisk/universal-gms-doze#1]
Hi, i'm installed Universal GMS Doze 1.8.2 on crDroid 7.3 (LOS18, A11, open_gapps-arm64-11.0-pico-20210130-TEST) and if i start Google Maps (installed from Play Store, not gapps package) it crashes immediately!

So i add
Code:

    <app-data-isolation-whitelisted-app package="com.google.android.gms" />
in..

/data/adb/modules/UniversalGMSDoze/system/etc/sysconfig/google.xml

Google Maps works great for now but i didn't know if this makes the module faulty or something!?

e.g. posted also on xda.

**Comment by gloeyisk** [comment]
> Google Maps works great for now but i didn't know if this makes the module faulty or something!?

This is known issue for Google Maps on any Android 11 based custom ROMs, you need to use older version for it, also you can safely remove those additional script.

**Comment by Cris--** [comment]
But what if i let it be with this extra permission. Newest Google Maps works and _dumpsys deviceidle_ looks good for me. 

Android 11 dumpsys deviceidle https://pastebin.com/NqQkKXG3

**Comment by gloeyisk** [comment]
> But what if i let it be with this extra permission. Newest Google Maps works and _dumpsys deviceidle_ looks good for me.
> 
> Android 11 dumpsys deviceidle https://pastebin.com/NqQkKXG3

I'm really appreciate your report but unfortunately those crash aren't caused by the module. As I checked your dumpsys outputs, the GMS does optimized and it's working. 
So I think better to use older version of Maps and wait until Google update the Maps overlay especially for Android 11.

**Comment by gjf** [comment]
I've spent a lot of time investigating this damned crash.
And I have to report this module is an issue.
1. Google Maps crashes immediately when logging in any account being online. In offline Google Maps are not crashing. Same - if no account was used in Google Maps app itself. But once logging in - crash in a second.
2. Any application using Google Play Services to display the map will show no map but "Google Play Services are updating" screen:
![ScreenshotB](https://user-images.githubusercontent.com/322186/115113484-4f0a0e00-9f93-11eb-854d-e549bf8fb5a3.jpg)
![ScreenshotA](https://user-images.githubusercontent.com/322186/115113487-503b3b00-9f93-11eb-9880-7ce322ebeab4.jpg)

When disabling the module - everything starts working properly. The issue is specific for Android 11 and was not present in earlier versions of Android.

**Comment by gloeyisk** [comment]
Make sure to test the new build, thanks!
