### ISSUE TITLE
Google Play Service *Not Optimized*

### ISSUE THREAD

**Issue by hameltonion** [gloeyisk/universal-gms-doze#55]
I tried that method to give the system some time like 2-3 minutes before unlocking the lockscreen but it didn't work , I also tried manually running service.sh script but still it says NOT OPTIMIZED. @gloeyisk 

I am on RUI 5.0 , A14

**Comment by chaoscreater** [comment]
Try manually toggling it to see if it can actually be battery optimized. Swift Backup also has the option to toggle it if you long press on an app. If you can toggle it, then it means the patch is working and you'll just need to figure out the command to make Play Services go into doze / battery-optimized.

I'm running the commands in the service.sh script using MacroDroid and it works fine. I'm doing this because I don't like the script having to wait 100 seconds every time my phone boots up. I can just let MacroDroid run my actions after it detects the phone has completed booting - which usually means that MacroDroid will complete running all my actions abotu 2~3 seconds after the phone has boot up.
